// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountSignature } from "./AccountSignature";

/**
 * A send-as identity or alias for an account (Roadmap 3.5).
 */
export type AccountIdentity = { id: string, accountId: number, name: string, email: string, replyTo: string | null, signature: AccountSignature, isDefault: boolean, };
