// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A signature configuration for an account / identity (Roadmap 3.5).
 */
export type AccountSignature = { plainText: string, html: string | null, includeInNewMail: boolean, includeInReplies: boolean, 
/**
 * `"above_quote"` | `"bottom"`
 */
replyPlacement: string, };
