// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What removing an account will destroy — the removal confirm's content.
 */
export type AccountRemovalInfo = { accountId: number, 
/**
 * Queued offline actions that would be discarded.
 */
queuedActions: number, 
/**
 * Locally saved but unsent drafts.
 */
drafts: number, localBytes: number, };
