// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The fields an existing account can be edited with (server/port/TLS/sync
 * cadence/color). The address and protocol identify the account and are
 * immutable; a password, if changed, is passed separately to the command.
 */
export type AccountEdit = { id: number, server: string, port: number, tls: boolean, 
/**
 * `"every 2 min"`, `"on open"`, or `"manual"`.
 */
syncMode: string, color: string, };
