// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * App settings (Epic 3.1 / 10). Today: the global treatment (D4) and the
 * persisted pane widths (Epic 4.2). `None` widths mean "use the theme
 * default" (`--sidebar-w` / `--list-w`).
 */
export type AppSettings = { 
/**
 * `"hairline"` | `"banded"`.
 */
theme: string, 
/**
 * Persisted sidebar width in CSS px, if the user resized it.
 */
sidebarWidth: number | null, 
/**
 * Persisted message-list width in CSS px, if the user resized it.
 */
listWidth: number | null, 
/**
 * Sender addresses whose remote images load by default (Epic 7.3) — the
 * per-sender "Load images" memory, never global-only.
 */
trustedImageSenders: Array<string>, };
