// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountIdentity } from "./AccountIdentity";
import type { MailRule } from "./MailRule";
import type { NotificationSettings } from "./NotificationSettings";

/**
 * App settings (Epic 3.1 / 10). Today: the global treatment (D4) and the
 * persisted pane widths (Epic 4.2). `None` widths mean "use the theme
 * default" (`--sidebar-w` / `--list-w`).
 */
export type AppSettings = { 
/**
 * `"hairline"` | `"banded"`.
 */
theme: string, 
/**
 * Persisted sidebar width in CSS px, if the user resized it.
 */
sidebarWidth: number | null, 
/**
 * Persisted message-list width in CSS px, if the user resized it.
 */
listWidth: number | null, 
/**
 * Sender addresses whose remote images load by default (Epic 7.3) — the
 * per-sender "Load images" memory, never global-only.
 */
trustedImageSenders: Array<string>, 
/**
 * Enable JWZ-style conversation threading in message lists (Roadmap 3.2).
 */
conversationThreading: boolean, 
/**
 * Notification preferences and quiet hours (Roadmap 3.4).
 */
notifications: NotificationSettings, 
/**
 * Configured send-as identities and aliases per account (Roadmap 3.5).
 */
identities: Array<AccountIdentity>, 
/**
 * Undo send delay in seconds (0 = disabled, 5..30 s) (Roadmap 3.5).
 */
undoSendDelaySec: number, 
/**
 * Local mail filtering and routing rules (Roadmap 3.6).
 */
rules: Array<MailRule>, 
/**
 * Whether remote images are blocked by default for untrusted senders (Roadmap 3.7).
 */
blockRemoteImages: boolean, 
/**
 * Primary calendar timezone (IANA ID e.g. "America/New_York"), null = local system time (Roadmap 4.3).
 */
primaryTimezone: string | null, 
/**
 * Secondary calendar timezone for dual-gutter time display (Roadmap 4.3).
 */
secondaryTimezone: string | null, 
/**
 * Whether to display the secondary timezone column in week/day views (Roadmap 4.3).
 */
showSecondaryTimezone: boolean, 
/**
 * Opt-in: upload scrubbed crash reports (Rust panics + JS errors) to the
 * configured endpoint. Default off — reports are always written locally,
 * transmission is the gated action (Roadmap 2.3).
 */
crashReportingEnabled: boolean, 
/**
 * Opt-in: anonymous usage ping (app version/OS only) on launch. Default off
 * (Roadmap 2.3).
 */
usagePingEnabled: boolean, 
/**
 * Unified log level: "error" | "warn" | "info" | "debug" | "trace"
 * (Roadmap 2.3 — unified logging).
 */
logLevel: string, };
