// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A message attachment card. The bytes travel over the asset protocol, not
 * through IPC (Epic 3.3); [`Attachment::on_disk`] drives the
 * "cached locally" label.
 */
export type Attachment = { id: number, message_id: number, filename: string, size_bytes: number, on_disk: boolean, };
