// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AttendeeInfo = { name: string | null, email: string, partstat: string, role: string | null, };
