// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a provider expects the user to authenticate.
 */
export type AuthKind = "oauth" | "app_password" | "password";
