// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of a bulk action — counts, so the UI can report partial failures.
 */
export type BulkActionResult = { ok: number, failed: number, errors: Array<string>, };
