// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One triage action applied to many messages at once (P1.1). `Move` carries
 * its destination folder as the command's `destination` argument.
 */
export type BulkAction = "markRead" | "markUnread" | "star" | "unstar" | "archive" | "delete" | "markJunk" | "markNotJunk" | "move";
