// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttendeeInfo } from "./AttendeeInfo";

export type CalendarInvite = { method: string, uid: string, sequence: number, title: string, startMs: number, endMs: number, allDay: boolean, location: string | null, organizerName: string | null, organizerEmail: string, userPartstat: string, attendees: Array<AttendeeInfo>, rawIcs: string, timezone: string | null, };
