// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Read-only external .ics / webcal calendar subscription (Roadmap 4.4).
 */
export type CalendarSubscription = { id: number, name: string, url: string, color: string, refreshIntervalMin: number, lastRefreshedAtMs: number | null, enabled: boolean, };
