// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A to-do task / VTODO item (Roadmap 4.5).
 */
export type CalendarTask = { id: number, accountId: number, title: string, dueAtMs: number | null, completedAtMs: number | null, priority: number | null, };
