// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A discovered or configured CalDAV calendar collection (Roadmap 1.4).
 */
export type CalendarCollection = { href: string, name: string, color: string | null, ctag: string | null, sync_token: string | null, };
