// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A distinct source calendar present in the local store (from sync). Drives
 * the calendar sidebar's per-calendar rows and show/hide toggles.
 */
export type CalendarSource = { accountId: number, source: string, name: string, color: string, };
