// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Calendar event. Recurrence is expanded in Rust (Epic 14) — the frontend
 * only ever sees resolved instances.
 */
export type CalendarEvent = { id: number, account_id: number, title: string, start_ms: number, end_ms: number, all_day: boolean, location: string | null, notes: string | null, };
