// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConnectivityUpdate = { 
/**
 * `"offline"` | `"syncing"` | `"synced"`.
 */
state: string, last_synced_at_ms: number | null, };
