// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectionIssue } from "./ConnectionIssue";

/**
 * Result of a connection test: reachability + auth per stage, with issues.
 */
export type ConnectionTestReport = { ok: boolean, authed: boolean, issues: Array<ConnectionIssue>, 
/**
 * Human detail, e.g. "N folders" or the SMTP greeting.
 */
detail: string, };
