// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorKind } from "./ErrorKind";
import type { Service } from "./Service";

/**
 * A single actionable connection problem: which service+server, what kind of
 * failure, and provider-specific help when known.
 */
export type ConnectionIssue = { service: Service, server: string, kind: ErrorKind, detail: string, help: string | null, };
