// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A recipient suggestion for the composer (P1.2): deduplicated by address
 * from mail history, ranked by frequency and recency.
 */
export type ContactSuggestion = { name: string, address: string, useCount: number, lastUsedAtMs: number, };
