// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A contact group (P1.2): a named list of addresses.
 */
export type ContactGroup = { id: number, name: string, };
