// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Read-only diagnostics status for the Settings → Diagnostics section
 * (Roadmap 2.3). Never contains message content or account addresses.
 */
export type DiagnosticsInfo = { 
/**
 * Running app version.
 */
appVersion: string, 
/**
 * OS family (`std::env::consts::OS`): "macos" | "windows" | "linux".
 */
os: string, 
/**
 * CPU architecture (`std::env::consts::ARCH`).
 */
arch: string, 
/**
 * "stable" or the pre-release tag (e.g. "beta.1") of the app version.
 */
channel: string, 
/**
 * Active unified log level.
 */
logLevel: string, 
/**
 * Whether the crash-reporting opt-in is currently on.
 */
crashReportingEnabled: boolean, 
/**
 * Whether the usage-ping opt-in is currently on.
 */
usagePingEnabled: boolean, 
/**
 * Count of crash reports queued locally, awaiting upload.
 */
pendingReportCount: number, 
/**
 * Absolute path to the local log file, if the log target is active.
 */
logFilePath: string | null, 
/**
 * Absolute path to the pending crash-reports directory.
 */
crashReportsDir: string, 
/**
 * Whether an upload endpoint is configured (build-time env vars).
 */
endpointConfigured: boolean, };
