// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiscoveryStep } from "./DiscoveryStep";
import type { Endpoint } from "./Endpoint";
import type { ProviderPreset } from "./ProviderPreset";

/**
 * Settings discovered for an email address, with provenance.
 */
export type DiscoveredSettings = { imap: Endpoint | null, smtp: Endpoint | null, caldav: Endpoint | null, provider: ProviderPreset | null, steps: Array<DiscoveryStep>, };
