// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One step of the autodiscovery pipeline with its outcome, so the UI can show
 * what was tried and why a fallback happened.
 */
export type DiscoveryStep = { 
/**
 * "preset" | "dns_srv" | "autoconfig" | "guess" | "manual".
 */
source: string, 
/**
 * "ok" | "skip" | "error".
 */
status: string, detail: string, };
