// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One mail/calendar endpoint (host, port, TLS) used by a preset or produced
 * by autodiscovery.
 */
export type Endpoint = { host: string, port: number, tls: boolean, };
