// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The class of a connection failure — what the UI distinguishes to offer the
 * right remedy (TLS vs auth vs network vs rate limit).
 */
export type ErrorKind = "dns" | "connect" | "tls" | "auth" | "rate_limit" | "timeout" | "protocol" | "offline";
