// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FolderKind } from "./FolderKind";

/**
 * A sidebar folder (unified set) with its live counts.
 */
export type Folder = { id: number, name: string, kind: FolderKind, unread_count: number, total_count: number, };
