// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Rename or reparent a mailbox.
 */
export type FolderEdit = { id: number, name: string | null, parentId: number | null, };
