// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A free/busy interval for scheduling (Roadmap 4.5).
 */
export type FreeBusySlot = { startMs: number, endMs: number, busy: boolean, attendee: string | null, };
