// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of an `.eml`/mbox import (P1.6): counts + per-message errors.
 */
export type ImportReport = { imported: number, duplicates: number, errors: Array<string>, };
