// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuleAction } from "./RuleAction";
import type { RuleCondition } from "./RuleCondition";
import type { RuleMatchMode } from "./RuleMatchMode";

/**
 * A local filtering / routing rule for incoming mail (Roadmap 3.6).
 */
export type MailRule = { id: string, name: string, enabled: boolean, matchMode: RuleMatchMode, conditions: Array<RuleCondition>, actions: Array<RuleAction>, stopProcessing: boolean, };
