// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A compose request from an OS integration (P1.5).
 */
export type MailtoPayload = { to: string, subject: string, body: string, };
