// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Attachment } from "./Attachment";
import type { CalendarInvite } from "./CalendarInvite";
import type { MessageRow } from "./MessageRow";
import type { Recipient } from "./Recipient";

/**
 * The full message, fetched on selection. The body is plain-text paragraphs
 * and/or sanitized HTML (Epic 7.3).
 */
export type MessageDetail = { row: MessageRow, to: Array<Recipient>, cc: Array<Recipient>, bcc: Array<Recipient>, body: Array<string>, 
/**
 * Sanitized HTML body, when the message arrived as HTML. Populated
 * server-side of the IPC boundary (Epic 7.3): the frontend never sees
 * raw mail HTML.
 */
body_html: string | null, 
/**
 * Remote images parked in `body_html` — drives the "Load images"
 * affordance (Epic 7.3).
 */
remote_image_count: number, attachments: Array<Attachment>, message_id_header: string | null, in_reply_to: string | null, references: string | null, thread_id: string | null, 
/**
 * iTIP/iMIP calendar invitation parsed from `text/calendar` part (Roadmap 4.1).
 */
calendar_invite: CalendarInvite | null, 
/**
 * RFC 8058 / RFC 2369 List-Unsubscribe header value (Roadmap 3.7).
 */
list_unsubscribe: string | null, 
/**
 * RFC 8058 List-Unsubscribe-Post header value (e.g. "List-Unsubscribe=One-Click") (Roadmap 3.7).
 */
list_unsubscribe_post: string | null, };
