// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Everything a message-list row renders — and nothing else (Epic 3.3).
 * Bodies are fetched only on selection via [`MessageDetail`].
 */
export type MessageRow = { id: number, account_id: number, 
/**
 * Folder the message currently lives in (`"Inbox"`, `"Drafts"`, …).
 */
folder: string, sender_name: string, sender_address: string, subject: string, snippet: string, 
/**
 * Unix millis. `number` in TS (JSON number, not bigint).
 */
received_at_ms: number, unread: boolean, flagged: boolean, has_attachments: boolean, };
