// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body-download progress for the reading pane. `phase` is one of
 * `"connecting"` | `"fetching"` | `"parsing"`; byte counters are non-zero only
 * during `"fetching"` (`total_bytes` is `0` until the server reports a size, so
 * the frontend shows an indeterminate bar until then).
 */
export type MessageProgressUpdate = { message_id: number, phase: string, received_bytes: number, total_bytes: number, };
