// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageRow } from "./MessageRow";

export type MessagePage = { items: Array<MessageRow>, total: number, };
