// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * List query. Filtering is by folder and/or account; the unified Inbox is a
 * query with `folder` unset.
 */
export type MessageQuery = { folder: string | null, account_id: number | null, offset: number, limit: number, threaded: boolean, };
