// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The fields the add-account form collects (Epic 10.4). The password is a
 * separate argument to the command and goes straight to the OS keychain —
 * it is deliberately not part of this type, so it cannot cross IPC back out.
 */
export type NewAccount = { address: string, 
/**
 * `"IMAP"` or `"Bridge"`.
 */
protocol: string, server: string, port: number, tls: boolean, 
/**
 * `"every 2 min"`, `"on open"`, or `"manual"`.
 */
sync_mode: string, };
