// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for creating a mailbox (T0.1).
 */
export type NewFolder = { accountId: number, parentId: number | null, name: string, };
