// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountNotificationSetting } from "./AccountNotificationSetting";

export type NotificationSettings = { enabled: boolean, sound: boolean, dockBadge: boolean, quietHoursEnabled: boolean, quietHoursStart: string, quietHoursEnd: string, knownContactsOnly: boolean, defaultAlarmMinutes: number | null, perAccount: Array<AccountNotificationSetting>, };
