// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Initialization payload for browser-based OAuth2 sign-in (Roadmap 3.1).
 */
export type OAuthInitPayload = { auth_url: string, code_verifier: string, redirect_uri: string, state: string, 
/**
 * The client ID actually used for the auth URL — surfaces the fallback
 * placeholder so the UI can show which client is in play.
 */
client_id: string, };
