// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of waiting for the OAuth loopback redirect.
 */
export type OAuthWaitResult = { ok: boolean, code: string | null, error: string | null, };
