// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OutgoingAttachment } from "./OutgoingAttachment";

/**
 * Outgoing mail. The transport lands in Epic 12/13; the contract is fixed here.
 */
export type OutgoingMessage = { account_id: number, from_name: string | null, from_address: string | null, reply_to: string | null, to: Array<string>, cc: Array<string>, bcc: Array<string>, subject: string, body: string, body_html: string | null, in_reply_to: string | null, references: string | null, attachments: Array<OutgoingAttachment>, original_message_id: number | null, is_forward: boolean | null, };
