// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OutgoingAttachment = { filename: string, content_type: string, data_base64: string, };
