// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Outgoing mail. The transport lands in Epic 12; the contract is fixed here.
 */
export type OutgoingMessage = { account_id: number, to: Array<string>, cc: Array<string>, subject: string, body: string, };
