// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthKind } from "./AuthKind";
import type { Endpoint } from "./Endpoint";

/**
 * A known mail provider preset (Gmail, iCloud, Fastmail, …) used to prefill
 * and guide account setup.
 */
export type ProviderPreset = { 
/**
 * Stable id ("gmail", "icloud", "fastmail", …).
 */
id: string, name: string, 
/**
 * Email domains this preset matches (e.g. ["icloud.com", "me.com"]).
 */
domains: Array<string>, imap: Endpoint, smtp: Endpoint, caldav: Endpoint | null, auth: AuthKind, 
/**
 * `"google"` / `"microsoft365"` when `auth == Oauth`.
 */
oauth_provider: string | null, 
/**
 * Provider-specific help shown at the point of failure (e.g. where to
 * create an app-specific password).
 */
help: string, };
