// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionType } from "./ActionType";

export type QueuedAction = {
  id: number;
  account_id: number;
  action_type: ActionType;
  folder: string;
  uid: number | null;
  uidvalidity: number | null;
  message_id_header: string | null;
  payload: string | null;
  created_at_ms: number;
  retries: number;
  /**
   * `pending` actions are replayable; `failed` actions reached the retry cap
   * and remain visible until the user retries or discards them.
   */
  status: string;
  next_attempt_at_ms: number;
  /**
   * The last replay failure, when the action couldn't be applied (P0.3).
   * `None` = pending or successful.
   */
  last_error: string | null;
};
