// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionType } from "./ActionType";

export type QueuedAction = { id: number, account_id: number, action_type: ActionType, folder: string, uid: number | null, payload: string | null, created_at_ms: number, retries: number, };
