// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An action to perform when a mail rule matches (Roadmap 3.6).
 */
export type RuleAction = { "moveToFolder": { folderName: string, } } | "markRead" | "markUnread" | "markFlagged" | "markUnflagged" | "delete" | "archive";
