// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One rule that matched a message in a dry-run, with its actions (P1.3).
 */
export type RulePreviewMatch = { ruleName: string, 
/**
 * Position in the rules list — the ordering explanation.
 */
ruleIndex: number, 
/**
 * Human-readable action descriptions.
 */
actions: Array<string>, };
