// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RulePreviewMatch } from "./RulePreviewMatch";

/**
 * A message a dry-run says the rules would change, with its before-state so
 * an applied run can be reverted (P1.3).
 */
export type RulePreview = { messageId: number, subject: string, sender: string, folderBefore: string, unreadBefore: boolean, flaggedBefore: boolean, matched: Array<RulePreviewMatch>, };
