// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Target field in message to evaluate (Roadmap 3.6).
 */
export type RuleField = "from" | "to" | "cc" | "subject" | "listId" | "hasAttachment" | "body";
