// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Match logic for rule conditions (Roadmap 3.6).
 */
export type RuleMatchMode = "all" | "any";
