// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RulePreview } from "./RulePreview";

/**
 * Result of a rule dry-run (P1.3): the affected count + per-message previews.
 */
export type RulePreviewResult = { affected: number, previews: Array<RulePreview>, };
