// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Comparison operator for rule conditions (Roadmap 3.6).
 */
export type RuleOperator = "contains" | "notContains" | "equals" | "notEquals" | "startsWith" | "endsWith" | "matches";
