// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuleField } from "./RuleField";
import type { RuleOperator } from "./RuleOperator";

/**
 * A condition predicate in a mail rule (Roadmap 3.6).
 */
export type RuleCondition = { field: RuleField, operator: RuleOperator, value: string, };
