// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A saved search (P1.3) — a persistent virtual folder that re-runs a query.
 */
export type SavedSearch = { id: number, name: string, query: string, createdAtMs: number, };
