// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A send-later message waiting in the durable Outbox (P1.1). The full
 * outgoing payload never crosses IPC — it lives in the store and is read only
 * by the flusher; the UI sees the display fields + the composer snapshot.
 */
export type ScheduledMessage = { id: number, accountId: number, sendAtMs: number, subject: string, to: Array<string>, createdAtMs: number, 
/**
 * Serialized composer snapshot so Edit can reopen the composer.
 */
draft: string, };
