// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A durable Outbox row. The full outgoing payload never crosses IPC — it
 * lives in the store and is read only by the sender; the UI sees display
 * fields, lifecycle state, and the composer snapshot for Edit.
 */
export type ScheduledMessage = {
  id: number;
  accountId: number;
  sendAtMs: number;
  subject: string;
  to: Array<string>;
  createdAtMs: number;
  /** `queued`, `sending`, `sent`, or `failed`. */
  status: string;
  retries: number;
  lastError: string | null;
  sentAtMs?: number;
  /** Serialized composer snapshot so Edit can reopen the composer. */
  draft: string;
};
