// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A search result item for messages or calendar events (Epic 15).
 */
export type SearchMatch = { 
/**
 * `"message"` or `"event"`.
 */
kind: string, id: number, account_id: number, folder: string | null, title: string, subtitle: string, snippet: string, timestamp_ms: number, };
