// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Search-index status/progress (P1.3).
 */
export type SearchIndexUpdate = { 
/**
 * "rebuilding" | "fresh" | "idle".
 */
state: string, indexed: number, total: number, };
