// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Search query payload with scoping and limit (Epic 15).
 */
export type SearchQuery = { query: string, folder: string | null, account_id: number | null, include_events: boolean, limit: number, };
