// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FolderKind } from "./FolderKind";

/**
 * A mailbox as discovered on the server, before it is saved to the local
 * store — the unit of "choose which folders sync".
 */
export type ServerFolder = { 
/**
 * Real IMAP mailbox name.
 */
serverName: string, 
/**
 * Local display name (the folder storage key).
 */
localName: string, kind: FolderKind, };
