// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FolderKind } from "./FolderKind";

/**
 * A persisted folder-sync selection for an account.
 */
export type SyncedFolder = { accountId: number, serverName: string, localName: string, kind: FolderKind, enabled: boolean, };
