// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Inputs for a full connection test (replaces the old raw-TCP probe).
 *
 * The password, when one is supplied for auth testing, is a separate command
 * argument (exactly like `add_account`) so the credential never lives in the
 * IPC contract.
 */
export type TestConnectionSettings = { email: string, 
/**
 * "imap" | "smtp" | "caldav".
 */
protocol: string, server: string, port: number, tls: boolean, };
